### ISSUE TITLE
Unconditional replacement

### ISSUE THREAD

**Issue by pornel** [matthew-andrews/Promise.prototype.finally#3]
Currently the code checks if there's a `finally` function present already and bails out:

```js
if (!finallySupport) local.Promise.prototype['finally'] = finallyPolyfill;
```

I'm wondering whether that's a good idea?

If some future ES2025 adds an incompatible implementation of `finally` then the existing programs will break.

OTOH if replacement was unconditional then the existing prolyfilled programs would continue to work. The only breaking case would be a bit anachronistic: if programs written for the future native `finally` included a prolyfill from the past.

**Comment by matthew-andrews** [comment]
Ummm I don't use this any more and wouldn't advocate its use. Maybe I should unpublish and delete the repo?

**Comment by pornel** [comment]
Nooooo! I can't live without `.finally` :)

**Comment by matthew-andrews** [comment]
released in `v1.0.1` & added you as collaborator

**Comment by rafis** [comment]
> Ummm I don't use this any more
Why you don't use it any more? Do you do `.then(cleanUp, cleanUp)` instead?

**Comment by matthew-andrews** [comment]
just find i don't do it often enough to justify bringing in a whole library… :sweat_smile:.  i guess if i found myself doing it more i'd use this library more……

**Comment by pornel** [comment]
`.then(cleanup, cleanup)` hides all errors, which is why I never use it.
