### ISSUE TITLE
Promise.reject instead of throw

### ISSUE THREAD

**Issue by kofifus** [matthew-andrews/Promise.prototype.finally#6]
wouldn't it be more correct to change the reject hundler to Promise.reject instead of throw ?

that is:
```
			}, function(reason) {
				return constructor.resolve(callback()).then(function() {
					return Promise.reject(reason);
				});
			});
```

see also discussion in http://stackoverflow.com/questions/28703241/promise-constructor-with-reject-call-vs-throwing-error

**Comment by ljharb** [comment]
No, `throw` is equally correct.
